server:
  port: 7000
  servlet:
    context-path: /ad-sponsor
spring:
  application:
    name: eureka-client-ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/ad_data?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2


eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/